FROM python:3.12-alpine3.20

RUN apk upgrade --update && apk add --no-cache \
  bash \
  git \
  cargo \
  linux-headers

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --no-dependencies -r requirements.txt

COPY src gulp_cfg_template.json MANIFEST.in pyproject.toml .
RUN --mount=source=.git,target=.git,type=bind pip install -e .

CMD [ "gulp", "--bind-to", "0.0.0.0", "8080" ]
